---
nginx_config:
  - src: domoticz.j2
    dest: /etc/nginx/sites-available/domoticz
  - src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  - src: nginx.service.j2
    dest: /etc/systemd/system/nginx.service
  - src: nginx.socket.j2
    dest: /etc/systemd/system/nginx.socket
  - src: nginx.j2
    dest: /etc/logrotate.d/nginx
  - src: tmpfiles.d.nginx.conf.j2
    dest: /etc/tmpfiles.d/nginx.conf

nginx_files:
  - src: /etc/nginx/sites-available/domoticz
    path: /etc/nginx/sites-enabled/domoticz
    state: link
  - src: /etc/nginx/sites-available/ha-bridge
    path: /etc/nginx/sites-enabled/ha-bridge
    state: link
  - path: /etc/nginx/sites-enabled/default
    state: absent
  - path: /var/lib/nginx
    state: directory
    owner: nginx
  - path: /var/log/nginx
    state: directory
    owner: nginx
  - path: /var/log/nginx/access.log
    state: file
    owner: nginx
  - path: /var/log/nginx/error.log
    state: file
    owner: nginx
