---
- block:
  - name: setup domoticz user
    user:
      name: domoticz
      home: /opt/domoticz
      shell: /bin/false
      system: true
      groups: dialout

  - block:
    - name: get domoticz
      get_url:
        url: "{{ domoticz_url }}/{{ domoticz_params | join('') }}"
        dest: /opt/domoticz
      register: result

    - name: extract files
      unarchive:
        src: /opt/domoticz/{{ result.dest | basename }}
        dest: /opt/domoticz
        remote_src: true

    - name: setup db dir
      file:
        path: /opt/domoticz/db
        mode: 0750
        state: directory

    become_user: domoticz

  - name: setup domoticz.service
    template:
      src: domoticz.service.j2
      dest: /etc/systemd/system/domoticz.service
      mode: 0644
    notify: restart domoticz

  - name: setup domoticz-update.service
    template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      mode: "{{ item.mode }}"
    with_items: "{{ domoticz_templates }}"

  - name: enable domoticz services
    systemd:
      name: "{{ item }}"
      enabled: true
      state: started
      daemon_reload: true
    with_items: "{{ domoticz_services }}"

  become: true
  tags: domoticz
